version: '2'
services:
    prometheus:
        build: ./
        restart: always
        ports:
            - "9090:9090"
#        depends_on:
#            - node_exporter
#            - mysqld_exporter

    grafana:
        image: grafana/grafana
#        build: ./
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=grafana
            - GF_DASHBOARDS_JSON_ENABLED=true
            - GF_DASHBOARDS_JSON_PATH=/home/dashboards
#        depends_on:
#            - influxdb
        ports:
            - 3000:3000
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro


#    node_exporter:
#        image: prom/node-exporter:v0.13.0
#        restart: always
#        ports: 
#            - "9100:9100"

#    mysqld_exporter:
#        image: prom/mysqld-exporter:v0.9.0
#        restart: always
#        ports:
#            - "9104:9104"
#        environment:
#            - DATA_SOURCE_NAME="prom:prom@(192.168.1.92:3306)/lingong"
