global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: linux
    static_configs:
      - targets: ['192.168.1.92:9100']
        labels:
          alias: db1
  - job_name: mysql
    static_configs:
      - targets: ['192.168.1.92:9104']
        labels:
          alias: db1
