global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090','node-exporter:9100','mysqld-exporter:9104','cadvisor:8080']
        labels:
          alias: db1

